# encoding: utf-8
lib = File.expand_path('../lib', __FILE__)
$:.unshift(lib) unless $:.include?(lib)

require 'version'

Gem::Specification.new do |spec|
  spec.name          = 'secretkey-uri'
  spec.version       = SecretKeyURI::VERSION
  spec.authors       = ['Dinusha Bodhinayake']
  spec.email         = ['dinushab@jobready.com.au']
  spec.description   = 'Generates a URL based on the token generated by the secretkey gem'
  spec.summary       = 'Provides developers a way of gaining a full URL for authenticating to any webservice that uses the secretkey gem for authenticating the user'
  spec.homepage      = 'https://github.com/jobready/secretkey-uri'
  spec.license       = 'MIT'
  
  spec.files         = `git ls-files`.split("\n")

  spec.add_dependency             'secretkey', SecretKeyURI::VERSION
  spec.add_development_dependency 'rspec'
  spec.add_development_dependency 'faker'
  spec.add_development_dependency 'simplecov'
  spec.add_development_dependency 'byebug'
end